### ISSUE TITLE
useGlobalCss priorization problem

### ISSUE THREAD

**Issue by cedricdelpoux** [css-system/css-system#19]
I have two different pages using the following global css
```
useGlobalCss(
    {
        body: {
            background,
        },
    },
    [background]
)
```

When I switch from one page to the other, a new classname is generated and the background color change. But if I go back to the first page, there is a problem is the rules order and the background color does not change

**Comment by myagoo** [comment]
Thank's for reporting this.
I'm gonna take a look at this, seems to be a problem with deps are used internally.
In the meantime and as a quick workaroud, you could try to use 2 statics useGlobalCss, each in one page. If a page is unmounted, the associated global style tag  will be removed.
